name: RELEASE
on:
  push:
    tags:
      - "v*.*.*"

concurrency:
  group: release_environment

jobs:
  build-nexus-cli:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17.1'
      - run: go version

      - name: Build
        shell: bash
        run: |
          make build
          make fmt
          make vet

      - name: Release
        shell: bash
        run: |
          make release

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*



